### ISSUE TITLE
Element 'referenceBlock', attribute 'cacheable': The attribute 'cacheable' is not allowed.

### ISSUE THREAD

**Issue by jqjk** [Magento-Japan/m2-jplocalize#11]
Veriteworks_Kanaを導入した状態でフロントの顧客情報編集画面(*/customer/account/edit/)にアクセスすると以下の例外となります。

    1 exception(s):
    Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'cacheable': The attribute 'cacheable' is not allowed.
    Line: 954

    Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'cacheable': The attribute 'cacheable' is not allowed.
    Line: 954

    #0 /var/www/magento2/lib/internal/Magento/Framework/Config/Dom.php(115): Magento\Framework\Config\Dom->_initDom('<layout xmlns:x...')
    #1 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Framework\Config\Dom->__construct('<layout xmlns:x...', Object(Magento\Framework\App\Arguments\ValidationState), Array, NULL, '/var/www/magent...', '%message%\nLine:...')
    #2 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
    #3 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...', Array)
    #4 /var/www/magento2/lib/internal/Magento/Framework/Config/DomFactory.php(42): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
    #5 /var/www/magento2/lib/internal/Magento/Framework/View/Model/Layout/Update/Validator.php(125): Magento\Framework\Config\DomFactory->createDom(Array)
    #6 /var/www/magento2/lib/internal/Magento/Framework/View/Model/Layout/Merge.php(461): Magento\Framework\View\Model\Layout\Update\Validator->isValid('<layout xmlns:x...', 'layout_merged', false)
    #7 /var/www/magento2/lib/internal/Magento/Framework/View/Model/Layout/Merge.php(442): Magento\Framework\View\Model\Layout\Merge->_validateMergedLayout('LAYOUT_frontend...', '<body>\n   <refe...')
    #8 /var/www/magento2/lib/internal/Magento/Framework/View/Layout/Builder.php(86): Magento\Framework\View\Model\Layout\Merge->load()
    #9 /var/www/magento2/lib/internal/Magento/Framework/View/Layout/Builder.php(63): Magento\Framework\View\Layout\Builder->loadLayoutUpdates()
    #10 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(254): Magento\Framework\View\Layout\Builder->build()
    #11 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(875): Magento\Framework\View\Layout->build()
    #12 /var/www/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('customer_edit')
    #13 /var/www/magento2/app/code/Magento/Customer/Controller/Account/Edit.php(68): Magento\Framework\View\Layout\Interceptor->getBlock('customer_edit')
    #14 /var/www/magento2/lib/internal/Magento/Framework/App/Action/Action.php(107): Magento\Customer\Controller\Account\Edit->execute()
    #15 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
    #16 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Account\Edit\Interceptor->___callParent('dispatch', Array)
    #17 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Account\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
    #18 /var/www/magento2/generated/code/Magento/Customer/Controller/Account/Edit/Interceptor.php(26): Magento\Customer\Controller\Account\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
    #19 /var/www/magento2/lib/internal/Magento/Framework/App/FrontController.php(55): Magento\Customer\Controller\Account\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
    #20 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
    #21 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
    #22 /var/www/magento2/app/code/Magento/Store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
    #23 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
    #24 /var/www/magento2/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
    #25 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
    #26 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
    #27 /var/www/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
    #28 /var/www/magento2/lib/internal/Magento/Framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
    #29 /var/www/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
    #30 /var/www/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
    #31 {main}

### Preconditions
Magento 2.2.0
### Steps to reproduce
フロントの顧客情報編集画面(*/customer/account/edit/)にアクセスする
### Expected result
正しく画面が表示される
### Actual result
例外となる
### Suggestion
対象ファイル：
`view\frontend\layout\customer_account_edit.xml`
対象箇所：
`<referenceBlock name="customer_edit" template="form/edit.phtml" cacheable="false">`
上記を以下のように書き換えることで解消致しました。修正のご検討をお願い致します。
`<referenceBlock name="customer_edit" template="form/edit.phtml">`

**Comment by HirokazuNishi** [comment]
ありがとうございます。2.2用はまだ色々調整中なので、安定版ではありません。
ご指摘の内容は速やかに取り入れたいと思います。

**Comment by jqjk** [comment]
早速のレスポンスありがとうございます。
日本語化エクステンション、とてもありがたく使用させて頂いております。
陰ながら応援させて頂くと同時に微力ながらお力添えしたく、また何かありましたら報告申し上げますので宜しくお願い致します。
